# Biri collection; GPL-3.0-only, see ../LICENSE.
[shaders.preset."window.cvd-deutan-oriented"]
scope = "window"

[[shaders.preset."window.cvd-deutan-oriented".passes]]
shader = "cvd-deutan-oriented.glsl"
