// Generated by generate-bleed-overlays.py; edit bleed/*.glsl.
// Biri collection; GPL-3.0, see ../LICENSE.
// Matches 6px borders and appearance.corner_radius = 10.
#define ring_size (umbriel_size / max(umbriel_scale, 0.01))
#define ring_width 6.0
#define ring_padding 14.0
#define ring_radius vec4(4.0)
float ring_distance(vec2 p) {
    vec2 half_size = ring_size * 0.5;
    float radius = min(4.0, min(half_size.x, half_size.y));
    vec2 q = abs(p - half_size) - half_size + radius;
    return length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - radius;
}
#define WAX_PHASE mod(umbriel_time / 22.0, 1.0)
// Adapted from Biri resources/shaders/focus-ring/rainbow-ripple.frag.
// Barrulus shader collection; GPL-3.0, see ../LICENSE.
// Glossy rainbow/neon ripple, paired with an inner-content overlay.
// These constants are shader-specific: change them or replace the whole algorithm.
#ifndef WAX_STRENGTH
#define WAX_STRENGTH 0.75
#endif
#ifndef WAX_BRIGHTNESS
#define WAX_BRIGHTNESS 1.0
#endif
#ifndef WAX_PHASE
#define WAX_PHASE mod(umbriel_time / 4.0, 1.0)
#endif
const float RIPPLE_INSET = 16.0;
const float RIPPLE_OUTSET = 12.0;

// Uneven periodic fields rather than equally spaced waves. Warping the sampling
// coordinate makes the lobes bunch up and stretch; all frequencies stay integral
// so the perimeter seam and the four-second animation loop remain continuous.
float wax_field(float u, float phase) {
    const float tau = 6.28318530718;
    return 0.46 * sin(tau * (3.0 * u - phase) + 0.7)
        + 0.28 * sin(tau * (7.0 * u + 2.0 * phase) + 2.1)
        + 0.17 * sin(tau * (11.0 * u - 2.0 * phase) + 4.4)
        + 0.09 * sin(tau * (19.0 * u + 3.0 * phase) + 1.3);
}

vec4 ripple_band(vec2 coords) {
    if (ring_width <= 0.0 || min(ring_size.x, ring_size.y) <= 0.0) return vec4(0.0);
    const float tau = 6.28318530718;
    float phase = WAX_PHASE;
    float strength = clamp(WAX_STRENGTH, 0.0, 1.0);
    float width = ring_width;
    vec2 nominal_size = ring_size + vec2(width * 2.0);
    vec2 p = (coords - ring_size * 0.5) / max(nominal_size * 0.5, vec2(1.0));
    float u = atan(p.y, p.x) / tau;
    float drift = u + 0.045 * wax_field(u + 0.13, phase);
    float bend = wax_field(drift, phase);
    float fine = wax_field(drift * 2.0 + 0.31, phase + 0.21);
    float pool = smoothstep(-0.65, 0.65, wax_field(drift + 0.43, phase + 0.37));

    float distance = ring_distance(coords);
    float extent = min(ring_width + ring_padding, RIPPLE_OUTSET);
    float half_px = 0.5 / max(umbriel_scale, 0.01);
    if (distance <= -RIPPLE_INSET || distance >= extent) return vec4(0.0);
    // Keep the original outer contour, but let its pools roll through the client
    // boundary. The matching window pass paints the inward half of this field.
    float original_inner = width * strength * max(0.0, 0.40 + 0.34 * bend + 0.20 * fine);
    float original_thickness = width * mix(1.0, 0.28 + 1.65 * pool + 0.20 * fine, strength);
    float outer_edge = min(original_inner + original_thickness, max(extent - 2.0 * half_px, 0.0));
    float inner_edge = -min(width * strength * (0.35 + 1.55 * pool + 0.18 * bend), RIPPLE_INSET - 2.0 * half_px);
    float thickness = max(outer_edge - inner_edge, 0.01);
    float coverage = smoothstep(inner_edge - half_px, inner_edge + half_px, distance)
        * (1.0 - smoothstep(outer_edge - half_px, outer_edge + half_px, distance));

    // Swirled pastel pigment and narrow, broken highlights give the pools a waxy
    // surface. The highlight meanders across the band instead of whitening its
    // entire cross-section like a light travelling through a tube.
    float across = clamp((distance - inner_edge) / max(thickness, 0.01), 0.0, 1.0);
    float pigment = u - phase + 0.10 * bend + 0.025 * fine
        + 0.025 * sin(tau * (across * 0.65 + drift * 8.0 + phase));
    vec3 hue = clamp(abs(fract(pigment + vec3(0.0, 2.0/3.0, 1.0/3.0)) * 6.0 - 3.0) - 1.0, 0.0, 1.0);
    float milk = clamp(0.30 + 0.18 * bend + 0.12 * pool, 0.12, 0.62);
    vec3 rgb = mix(hue, vec3(1.0), milk);
    float ridge = 0.48 + 0.18 * fine;
    float sheen = exp(-pow((across - ridge) / 0.17, 2.0))
        * smoothstep(0.30, 0.85, pool) * (0.65 + 0.35 * bend);
    rgb = mix(rgb, vec3(1.0), 0.8 * sheen);
    rgb *= 0.90 + 0.10 * sin(tau * (across * 0.5 + 0.1 * bend));
    rgb = clamp(rgb * WAX_BRIGHTNESS, 0.0, 1.0);
    float envelope = smoothstep(-RIPPLE_INSET, -RIPPLE_INSET + 2.0 * half_px, distance)
        * (1.0 - smoothstep(max(extent - 2.0 * half_px, 0.0), extent, distance));
    return vec4(rgb, coverage * envelope);
}
const float BLEED_SPEED = 0.24;
// Slow liquid vignette and detached lobes. Logical pixels; straight RGBA.
const float BLEED_INSET = 112.0;
const float BLEED_TAU = 6.28318530718;

float bleed_hash(float n) {
    return fract(sin(n * 127.1 + 311.7) * 43758.5453);
}

// Project onto the perimeter so pigment stays continuous across corner diagonals.
float bleed_along(vec2 p) {
    vec2 q = p - ring_size * 0.5;
    vec2 normalized = abs(q) / max(ring_size * 0.5, vec2(0.001));
    q /= max(max(normalized.x, normalized.y), 0.001);
    p = q + ring_size * 0.5;
    vec2 edge = abs(q) - ring_size * 0.5;
    if (edge.y >= edge.x)
        return q.y < 0.0 ? p.x : ring_size.x * 2.0 + ring_size.y - p.x;
    return q.x > 0.0 ? ring_size.x + p.y : 2.0 * (ring_size.x + ring_size.y) - p.y;
}

// A wide pool at each corner, tapering into a shallower frame along the sides.
float bleed_corner(vec2 p) {
    vec2 edge = max(min(p, ring_size - p), vec2(0.0));
    float reach = min(170.0, min(ring_size.x, ring_size.y) * 0.38);
    return exp(-dot(edge, edge) / max(reach * reach, 1.0));
}

// Each material supplies the moving band and pigment for its detached globules.
vec4 bleed_band(vec2 p);
vec3 bleed_pigment(float along, float depth, float seed, float sheen);

vec4 ring_color(vec2 p) {
    if (ring_width <= 0.0 || min(ring_size.x, ring_size.y) <= 0.0) return vec4(0.0);
    float d = ring_distance(p);
    if (d <= -BLEED_INSET || d >= 14.0) return vec4(0.0);
    vec4 base = bleed_band(p);
    float perimeter = 2.0 * (ring_size.x + ring_size.y);
    float along = mod(bleed_along(p), perimeter);
    float corner = bleed_corner(p);
    float limit = min(BLEED_INSET, min(ring_size.x, ring_size.y) * 0.28);
    float t = umbriel_time * BLEED_SPEED;
    // Screen-space waves remain continuous across the corner diagonals.
    float wave = 0.5 + 0.30 * sin(p.x * 0.027 + t * 0.7
        + sin(p.y * 0.019 - t * 0.5))
        + 0.20 * sin(p.y * 0.034 - t * 0.6 + sin(p.x * 0.013 + t * 0.4));
    float frame_depth = min(10.0 + 15.0 * wave + corner * (36.0 + 30.0 * wave), limit * 0.84);
    float depth_in = max(-d, 0.0);
    float frame = (1.0 - smoothstep(frame_depth * 0.48, frame_depth, depth_in))
        * (1.0 - smoothstep(0.0, 3.0, d));
    frame *= mix(0.62, 0.90, corner);
    float highlight = exp(-pow((depth_in - frame_depth * 0.38) / 3.5, 2.0)) * 0.30;
    vec3 frame_color = bleed_pigment(along, depth_in, wave, highlight);
    float frame_alpha = base.a + frame * (1.0 - base.a);
    base.rgb = (base.rgb * base.a + frame_color * frame * (1.0 - base.a)) / max(frame_alpha, 0.0001);
    base.a = frame_alpha;
    float cells = max(floor(perimeter / 132.0), 4.0);
    float spacing = perimeter / cells;
    float cell = floor(along / spacing);
    float aa = 0.65 / max(umbriel_scale, 0.01);
    // Only local emitters: cost stays constant as window perimeter grows.
    for (int neighbor = -1; neighbor <= 1; neighbor++) {
        float id = mod(cell + float(neighbor), cells);
        float seed = bleed_hash(id + 19.0);
        float clock = umbriel_time * BLEED_SPEED / (1.8 + seed * 1.8) + seed * 9.0;
        float cycle = floor(clock);
        float event = id * 53.7 + cycle * 17.13;
        float r = bleed_hash(event + 5.0);
        float r2 = bleed_hash(event + 29.0);
        float age = fract(clock) / (0.72 + r2 * 0.20);
        if (age >= 1.0) continue;
        float born = smoothstep(0.0, 0.12, age);
        float dying = 1.0 - smoothstep(0.43, 1.0, age);
        float travel = smoothstep(0.0, 1.0, age);
        float head = (id + 0.20 + 0.60 * r) * spacing;
        float drift = (r2 - 0.5) * 21.0 * travel
            + sin(age * 5.7 + r * 12.0) * 3.0 * travel;
        float delta = mod(along - head - drift + perimeter * 0.5, perimeter) - perimeter * 0.5;
        float depth = 5.0 + travel * min(30.0 + 16.0 * r2 + 36.0 * corner, limit * 0.82);
        float radius = (8.0 + 7.0 * r) * (1.0 + 0.85 * corner) * born * pow(dying, 0.65);
        vec2 q = vec2(delta, d + depth);
        // Unequal lobes roll, stretch, pinch off, then shrink to nothing.
        float angle = age * (r2 - 0.5) * 5.0;
        q = mat2(cos(angle), -sin(angle), sin(angle), cos(angle)) * q;
        q.x *= 0.86 + 0.24 * r2;
        float shape = min(length(q), length(q - vec2(radius * 0.48, radius * 0.32)) + radius * 0.24) - radius;
        float drop = (1.0 - smoothstep(-aa, aa, shape)) * born * dying;
        // A thinning neck follows the lobe only at birth, leaving a real gap.
        float neck_radius = radius * 0.62 * (1.0 - smoothstep(0.12, 0.42, age));
        float neck = max(abs(delta) - neck_radius, max(d - 1.0, -depth - d));
        float neck_alpha = (1.0 - smoothstep(-aa, aa, neck)) * born
            * (1.0 - smoothstep(0.20, 0.44, age));
        float alpha = max(drop, neck_alpha) * (1.0 - smoothstep(limit * 0.72, limit, -d));
        float sheen = exp(-dot(q - vec2(-radius * 0.27, radius * 0.3),
            q - vec2(-radius * 0.27, radius * 0.3)) / max(radius * radius * 0.12, 0.05));
        vec3 color = bleed_pigment(head, depth, r, sheen);
        float out_alpha = alpha + base.a * (1.0 - alpha);
        base.rgb = (color * alpha + base.rgb * base.a * (1.0 - alpha)) / max(out_alpha, 0.0001);
        base.a = out_alpha;
    }
    return base;
}
// Retain rainbow-ripple's waxy neon band, with irregular inward shedding.


vec4 bleed_band(vec2 p) { return ripple_band(p); }

vec3 bleed_pigment(float along, float depth, float seed, float sheen) {
    float perimeter = 2.0 * (ring_size.x + ring_size.y);
    // Match the original band's angular rainbow at the droplet's birthplace.
    vec2 p;
    if (along < ring_size.x) p = vec2(along, 0.0);
    else if (along < ring_size.x + ring_size.y) p = vec2(ring_size.x, along - ring_size.x);
    else if (along < 2.0 * ring_size.x + ring_size.y)
        p = vec2(2.0 * ring_size.x + ring_size.y - along, ring_size.y);
    else p = vec2(0.0, perimeter - along);
    vec2 q = (p - ring_size * 0.5) / max(ring_size * 0.5, vec2(1.0));
    float u = atan(q.y, q.x) / 6.28318530718;
    float drift = u + 0.045 * wax_field(u + 0.13, WAX_PHASE);
    float hue = u - WAX_PHASE + 0.10 * wax_field(drift, WAX_PHASE);
    vec3 rgb = clamp(abs(fract(hue + vec3(0.0, 2.0/3.0, 1.0/3.0)) * 6.0 - 3.0) - 1.0, 0.0, 1.0);
    return mix(mix(rgb, vec3(1.0), 0.22), vec3(1.0), sheen * 0.70);
}

vec4 postprocess(vec3 coords) {
    vec4 source = tex2D_screen(coords.xy);
    vec2 p = coords.xy * ring_size;
    if (min(min(p.x, p.y), min(ring_size.x - p.x, ring_size.y - p.y)) > BLEED_INSET)
        return source;
    vec4 liquid = ring_color(p);
    return vec4(source.rgb * (1.0 - liquid.a) + liquid.rgb * liquid.a * source.a, source.a);
}
