// Generated by generate-bleed-overlays.py; edit bleed/*.glsl.
// Biri collection; GPL-3.0, see ../LICENSE.
// Matches 6px borders and appearance.corner_radius = 10.
#define ring_size (umbriel_size / max(umbriel_scale, 0.01))
#define ring_width 6.0
#define ring_padding 14.0
#define ring_radius vec4(4.0)
float ring_distance(vec2 p) {
    vec2 half_size = ring_size * 0.5;
    float radius = min(4.0, min(half_size.x, half_size.y));
    vec2 q = abs(p - half_size) - half_size + radius;
    return length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - radius;
}
const float BLEED_SPEED = 0.22;
// Slow liquid vignette and detached lobes. Logical pixels; straight RGBA.
const float BLEED_INSET = 112.0;
const float BLEED_TAU = 6.28318530718;

float bleed_hash(float n) {
    return fract(sin(n * 127.1 + 311.7) * 43758.5453);
}

// Project onto the perimeter so pigment stays continuous across corner diagonals.
float bleed_along(vec2 p) {
    vec2 q = p - ring_size * 0.5;
    vec2 normalized = abs(q) / max(ring_size * 0.5, vec2(0.001));
    q /= max(max(normalized.x, normalized.y), 0.001);
    p = q + ring_size * 0.5;
    vec2 edge = abs(q) - ring_size * 0.5;
    if (edge.y >= edge.x)
        return q.y < 0.0 ? p.x : ring_size.x * 2.0 + ring_size.y - p.x;
    return q.x > 0.0 ? ring_size.x + p.y : 2.0 * (ring_size.x + ring_size.y) - p.y;
}

// A wide pool at each corner, tapering into a shallower frame along the sides.
float bleed_corner(vec2 p) {
    vec2 edge = max(min(p, ring_size - p), vec2(0.0));
    float reach = min(170.0, min(ring_size.x, ring_size.y) * 0.38);
    return exp(-dot(edge, edge) / max(reach * reach, 1.0));
}

// Each material supplies the moving band and pigment for its detached globules.
vec4 bleed_band(vec2 p);
vec3 bleed_pigment(float along, float depth, float seed, float sheen);

vec4 ring_color(vec2 p) {
    if (ring_width <= 0.0 || min(ring_size.x, ring_size.y) <= 0.0) return vec4(0.0);
    float d = ring_distance(p);
    if (d <= -BLEED_INSET || d >= 14.0) return vec4(0.0);
    vec4 base = bleed_band(p);
    float perimeter = 2.0 * (ring_size.x + ring_size.y);
    float along = mod(bleed_along(p), perimeter);
    float corner = bleed_corner(p);
    float limit = min(BLEED_INSET, min(ring_size.x, ring_size.y) * 0.28);
    float t = umbriel_time * BLEED_SPEED;
    // Screen-space waves remain continuous across the corner diagonals.
    float wave = 0.5 + 0.30 * sin(p.x * 0.027 + t * 0.7
        + sin(p.y * 0.019 - t * 0.5))
        + 0.20 * sin(p.y * 0.034 - t * 0.6 + sin(p.x * 0.013 + t * 0.4));
    float frame_depth = min(10.0 + 15.0 * wave + corner * (36.0 + 30.0 * wave), limit * 0.84);
    float depth_in = max(-d, 0.0);
    float frame = (1.0 - smoothstep(frame_depth * 0.48, frame_depth, depth_in))
        * (1.0 - smoothstep(0.0, 3.0, d));
    frame *= mix(0.62, 0.90, corner);
    float highlight = exp(-pow((depth_in - frame_depth * 0.38) / 3.5, 2.0)) * 0.30;
    vec3 frame_color = bleed_pigment(along, depth_in, wave, highlight);
    float frame_alpha = base.a + frame * (1.0 - base.a);
    base.rgb = (base.rgb * base.a + frame_color * frame * (1.0 - base.a)) / max(frame_alpha, 0.0001);
    base.a = frame_alpha;
    float cells = max(floor(perimeter / 132.0), 4.0);
    float spacing = perimeter / cells;
    float cell = floor(along / spacing);
    float aa = 0.65 / max(umbriel_scale, 0.01);
    // Only local emitters: cost stays constant as window perimeter grows.
    for (int neighbor = -1; neighbor <= 1; neighbor++) {
        float id = mod(cell + float(neighbor), cells);
        float seed = bleed_hash(id + 19.0);
        float clock = umbriel_time * BLEED_SPEED / (1.8 + seed * 1.8) + seed * 9.0;
        float cycle = floor(clock);
        float event = id * 53.7 + cycle * 17.13;
        float r = bleed_hash(event + 5.0);
        float r2 = bleed_hash(event + 29.0);
        float age = fract(clock) / (0.72 + r2 * 0.20);
        if (age >= 1.0) continue;
        float born = smoothstep(0.0, 0.12, age);
        float dying = 1.0 - smoothstep(0.43, 1.0, age);
        float travel = smoothstep(0.0, 1.0, age);
        float head = (id + 0.20 + 0.60 * r) * spacing;
        float drift = (r2 - 0.5) * 21.0 * travel
            + sin(age * 5.7 + r * 12.0) * 3.0 * travel;
        float delta = mod(along - head - drift + perimeter * 0.5, perimeter) - perimeter * 0.5;
        float depth = 5.0 + travel * min(30.0 + 16.0 * r2 + 36.0 * corner, limit * 0.82);
        float radius = (8.0 + 7.0 * r) * (1.0 + 0.85 * corner) * born * pow(dying, 0.65);
        vec2 q = vec2(delta, d + depth);
        // Unequal lobes roll, stretch, pinch off, then shrink to nothing.
        float angle = age * (r2 - 0.5) * 5.0;
        q = mat2(cos(angle), -sin(angle), sin(angle), cos(angle)) * q;
        q.x *= 0.86 + 0.24 * r2;
        float shape = min(length(q), length(q - vec2(radius * 0.48, radius * 0.32)) + radius * 0.24) - radius;
        float drop = (1.0 - smoothstep(-aa, aa, shape)) * born * dying;
        // A thinning neck follows the lobe only at birth, leaving a real gap.
        float neck_radius = radius * 0.62 * (1.0 - smoothstep(0.12, 0.42, age));
        float neck = max(abs(delta) - neck_radius, max(d - 1.0, -depth - d));
        float neck_alpha = (1.0 - smoothstep(-aa, aa, neck)) * born
            * (1.0 - smoothstep(0.20, 0.44, age));
        float alpha = max(drop, neck_alpha) * (1.0 - smoothstep(limit * 0.72, limit, -d));
        float sheen = exp(-dot(q - vec2(-radius * 0.27, radius * 0.3),
            q - vec2(-radius * 0.27, radius * 0.3)) / max(radius * radius * 0.12, 0.05));
        vec3 color = bleed_pigment(head, depth, r, sheen);
        float out_alpha = alpha + base.a * (1.0 - alpha);
        base.rgb = (color * alpha + base.rgb * base.a * (1.0 - alpha)) / max(out_alpha, 0.0001);
        base.a = out_alpha;
    }
    return base;
}
// Slow violet and orchid pools with sparse, erratic magical filaments.


vec3 bleed_pigment(float along, float depth, float seed, float sheen) {
    float perimeter = 2.0 * (ring_size.x + ring_size.y);
    float u = along / perimeter;
    float t = umbriel_time * BLEED_SPEED;
    float turns = max(floor(perimeter / 210.0), 1.0);
    float phase = u * BLEED_TAU * turns;
    float swirl = sin(phase - t * 0.8 + depth * 0.046
        + 1.3 * sin(phase * 2.0 + t * 0.45 - depth * 0.035));
    float pools = sin(phase + t * 0.55 + depth * 0.065 + 1.2 * swirl);
    vec3 violet = vec3(0.42, 0.035, 0.88);
    vec3 orchid = vec3(0.78, 0.14, 0.98);
    vec3 amethyst = vec3(0.56, 0.27, 1.0);
    vec3 pigment = mix(violet, orchid, smoothstep(-0.65, 0.75, swirl));
    pigment = mix(pigment, amethyst, 0.38 * (0.5 + 0.5 * pools));
    // Fine, broken contour lines fizz faster than the underlying liquid moves.
    float fizz = umbriel_time * 1.25;
    float filament_field = sin(phase * 3.0 + depth * 0.21 + 1.6 * swirl
        + 0.28 * sin(phase * 11.0 - fizz + depth * 0.36));
    float filament = 1.0 - smoothstep(0.025, 0.095, abs(filament_field));
    float sparks = smoothstep(0.52, 0.88,
        sin(phase * 5.0 + depth * 0.09 + sin(phase * 9.0 + fizz)));
    pigment = mix(pigment, vec3(0.62, 0.95, 0.24), filament * sparks * 0.72);
    float seam = (1.0 - smoothstep(0.025, 0.085, abs(filament_field + 0.36)))
        * smoothstep(0.45, 0.90, pools);
    pigment = mix(pigment, vec3(0.14, 0.025, 0.27), seam * 0.40);
    return mix(pigment, vec3(0.87, 0.65, 1.0), sheen * 0.48);
}

vec4 bleed_band(vec2 p) {
    float d = ring_distance(p);
    float perimeter = 2.0 * (ring_size.x + ring_size.y);
    float u = bleed_along(p) / perimeter;
    float t = umbriel_time * BLEED_SPEED;
    float frequency = max(floor(perimeter / 175.0), 1.0);
    float warp = 1.5 * sin(u * BLEED_TAU * 5.0 + t * 0.7);
    float lava = sin(u * BLEED_TAU * frequency - t * 2.0 + warp);
    float fine = sin(u * BLEED_TAU * (frequency + 7.0) + t * 1.25 + lava);
    float inner = -2.4 - 3.1 * (0.5 + 0.5 * lava) - 1.1 * fine;
    float outer = 6.2 + 1.6 * lava + 0.9 * fine;
    float aa = 0.65 / max(umbriel_scale, 0.01);
    float coverage = smoothstep(inner - aa, inner + aa, d)
        * (1.0 - smoothstep(outer - aa, outer + aa, d));
    float across = (d - inner) / max(outer - inner, 0.1);
    float sheen = exp(-pow((across - 0.69 - fine * 0.1) / 0.095, 2.0))
        * (0.4 + 0.6 * smoothstep(-0.3, 0.8, lava));
    vec3 rgb = bleed_pigment(u * perimeter, -d, 0.0, sheen);
    // Purple remains the body of the liquid; filaments only tint narrow traces.
    return vec4(rgb * (0.8 + 0.2 * sin(across * 3.14159)), coverage);
}

vec4 postprocess(vec3 coords) {
    vec4 source = tex2D_screen(coords.xy);
    vec2 p = coords.xy * ring_size;
    if (min(min(p.x, p.y), min(ring_size.x - p.x, ring_size.y - p.y)) > BLEED_INSET)
        return source;
    vec4 liquid = ring_color(p);
    return vec4(source.rgb * (1.0 - liquid.a) + liquid.rgb * liquid.a * source.a, source.a);
}
