[effects.whirlpool.open]
duration_ms = 400
curve = "linear"
passes = [{ shader = "whirlpool-open.glsl" }]

[effects.whirlpool.close]
duration_ms = 500
curve = "linear"
passes = [{ shader = "whirlpool-close.glsl" }]
