[animation.pair.whirlpool.open]
shader = "animations/whirlpool-open.glsl"
duration_ms = 400
curve = "linear"

[animation.pair.whirlpool.close]
shader = "animations/whirlpool-close.glsl"
duration_ms = 500
curve = "linear"

[animation.pair.melt.open]
shader = "animations/melt-open.glsl"
duration_ms = 400
curve = "linear"

[animation.pair.melt.close]
shader = "animations/melt-close.glsl"
duration_ms = 500
curve = "linear"

[animation.pair.ripple.open]
shader = "animations/ripple-open.glsl"
duration_ms = 400
curve = "linear"

[animation.pair.ripple.close]
shader = "animations/ripple-close.glsl"
duration_ms = 500
curve = "linear"

[animation.pair.lightning.open]
shader = "animations/lightning-open.glsl"
duration_ms = 400
curve = "linear"

[animation.pair.lightning.close]
shader = "animations/lightning-close.glsl"
duration_ms = 400
curve = "linear"
