[effects.lightning.border.outer]
enabled = true
animated = true
speed = 1
padding = 24
passes = [{ shader = "lightning.glsl" }]

[effects.lightning.border.outer.light]
enabled = true
spread = 80
intensity = 1.0
threshold = 0.5

[effects.lightning.border.inner]
enabled = false
