#!/usr/bin/env python3
"""Regenerate the window half after editing rings/flowering-vine.glsl.

The two hosts cannot include shared GLSL files, so generate the window adapter
from the canonical ring shader. No geometry or animation is maintained twice.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
HEADER = """// Generated by shaders/generate-vine-overlay.py; edit the ring source.
// These match the flowering-vine preset and appearance.corner_radius = 10.
// Umbriel's client radius is the decorated radius minus the 6px border.
#define ring_size (umbriel_size / max(umbriel_scale, 0.01))
#define ring_width 6.0
#define ring_padding 8.0
#define ring_radius vec4(4.0)

float ring_distance(vec2 coords) {
    vec2 half_size = ring_size * 0.5;
    float radius = min(4.0, min(half_size.x, half_size.y));
    vec2 q = abs(coords - half_size) - half_size + radius;
    return length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - radius;
}

"""
FOOTER = """
// Blend premultiplied content with the same straight-RGBA flowers as the border.
vec4 postprocess(vec3 coords) {
    vec4 source = tex2D_screen(coords.xy);
    vec2 p = coords.xy * ring_size;
    if (min(min(p.x, p.y), min(ring_size.x - p.x, ring_size.y - p.y)) > VINE_INSET)
        return source;
    vec4 flowers = ring_color(p);
    return vec4(source.rgb * (1.0 - flowers.a) + flowers.rgb * flowers.a * source.a, source.a);
}
"""
(ROOT / "window/flowering-vine-overlay.glsl").write_text(
    HEADER + (ROOT / "rings/flowering-vine.glsl").read_text() + FOOTER
)
