#!/usr/bin/env python3
"""Build both ring hosts and their matching inward window overlays.

Edit bleed/*.glsl, then run
this script. Umbriel's shader hosts do not support GLSL includes.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
COMMON = (ROOT / "bleed/droplets.glsl").read_text()
HEADER = """// Generated by generate-bleed-overlays.py; edit bleed/*.glsl.
"""
ADAPTER = """// Matches 6px borders and appearance.corner_radius = 10.
#define ring_size (umbriel_size / max(umbriel_scale, 0.01))
#define ring_width 6.0
#define ring_padding 14.0
#define ring_radius vec4(4.0)
float ring_distance(vec2 p) {
    vec2 half_size = ring_size * 0.5;
    float radius = min(4.0, min(half_size.x, half_size.y));
    vec2 q = abs(p - half_size) - half_size + radius;
    return length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - radius;
}
"""
FOOTER = """
vec4 postprocess(vec3 coords) {
    vec4 source = tex2D_screen(coords.xy);
    vec2 p = coords.xy * ring_size;
    if (min(min(p.x, p.y), min(ring_size.x - p.x, ring_size.y - p.y)) > BLEED_INSET)
        return source;
    vec4 liquid = ring_color(p);
    return vec4(source.rgb * (1.0 - liquid.a) + liquid.rgb * liquid.a * source.a, source.a);
}
"""
for name, material in (("neon-bleed", "neon"), ("portal-lava", "portal")):
    style = (ROOT / f"bleed/{material}.glsl").read_text()
    # Speed is needed in the common body; material functions follow prototypes.
    speed = next(line for line in style.splitlines() if line.startswith("const float BLEED_SPEED"))
    body = speed + "\n" + COMMON + style.replace(speed, "")
    (ROOT / f"rings/{name}.glsl").write_text(HEADER + body)
    (ROOT / f"window/{name}-overlay.glsl").write_text(HEADER + ADAPTER + body + FOOTER)
